# Generated by Django 5.1.1 on 2024-09-28 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learners', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learners',
            name='Attended_Demo',
            field=models.CharField(choices=[('None', 'None'), ('Ready To Join', 'Ready To Join'), ('Advanced Discussion', 'Advanced Discussion'), ('Call Not Answered', 'Call Not Answered'), ('Visiting', 'Visiting'), ('Fees Negotiation', 'Fees Negotiation'), ('Batch Allocation', 'Batch Allocation'), ('Need Time This Week', 'Need Time This Week'), ('Need Time Next Week', 'Need Time Next Week'), ('Need Time This Month', 'Need Time This Month'), ('Need Time Next Month', 'Need Time Next Month'), ('Special Requirements', 'Special Requirements'), ('Closed Own Register', 'Closed Own Register'), ('Closed Lost Cold Lead', 'Closed Lost Cold Lead')], default='None', max_length=30),
        ),
        migrations.AlterField(
            model_name='learners',
            name='Learner_Stage',
            field=models.CharField(choices=[('None', 'None'), ('Call Not Answered', 'Call Not Answered'), ('Ready To Join', 'Ready To Join'), ('Fees Negotiation', 'Fees Negotiation'), ('Batch Allocation', 'Batch Allocation'), ('Interested Demo', 'Interested Demo'), ('Special Requirements', 'Special Requirements'), ('Need Time This Week', 'Need Time This Week'), ('Need Time Next Week', 'Need Time Next Week'), ('Need Time This Month', 'Need Time This Month'), ('Need Time Next Month', 'Need Time Next Month'), ('Closed Own Register', 'Closed Own Register')], default='None', max_length=30),
        ),
        migrations.AlterField(
            model_name='learners',
            name='Location',
            field=models.CharField(choices=[('None', 'None'), ('Advanced Discussion', 'Advanced Discussion'), ('Ready To Join', 'Ready To Join'), ('Visiting', 'Visiting'), ('Fees Negotiation', 'Fees Negotiation'), ('Batch Allocation', 'Batch Allocation'), ('Interested Demo', 'Interested Demo'), ('Need Time This Week', 'Need Time This Week'), ('Need Time Next Week', 'Need Time Next Week'), ('Need Time This Month', 'Need Time This Month'), ('Need Time Next Month', 'Need Time Next Month'), ('Special Requirements', 'Special Requirements'), ('Payment Link Sent', 'Payment Link Sent'), ('Closed Own Register', 'Closed Own Register'), ('Busy Asked A Call Back', 'Busy Asked A Call Back'), ('Closed Lost', 'Closed Lost')], default='None', max_length=30),
        ),
    ]
