# Generated by Django 5.1.1 on 2024-10-01 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learners', '0002_alter_learners_attended_demo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learners',
            name='CounselingDoneBY',
        ),
        migrations.AddField(
            model_name='learners',
            name='counseling_done_by',
            field=models.CharField(choices=[('True', 'True'), ('False', 'False')], default='False', max_length=5),
        ),
    ]
