# Generated by Django 5.1.1 on 2024-10-01 09:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learners', '0003_remove_learners_counselingdoneby_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learners',
            name='Leadcratedtime',
        ),
        migrations.AddField(
            model_name='learners',
            name='Leadcreatedtime',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
