# Generated by Django 5.1.1 on 2024-10-02 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learners', '0004_remove_learners_leadcratedtime_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learners',
            old_name='Alternatephone',
            new_name='Alternate_Phone',
        ),
        migrations.RenameField(
            model_name='learners',
            old_name='BatchId',
            new_name='Batch_Id',
        ),
        migrations.RenameField(
            model_name='learners',
            old_name='BatchTiming',
            new_name='Batch_Timing',
        ),
        migrations.RenameField(
            model_name='learners',
            old_name='counseling_done_by',
            new_name='Counseling_Done_By',
        ),
        migrations.RenameField(
            model_name='learners',
            old_name='CourseComments',
            new_name='Course_Comments',
        ),
        migrations.RenameField(
            model_name='learners',
            old_name='DateofBirth',
            new_name='Date_OF_Birth',
        ),
        migrations.RenameField(
            model_name='learners',
            old_name='ExchangeRate',
            new_name='Exchange_Rate',
        ),
        migrations.RenameField(
            model_name='learners',
            old_name='FirstName',
            new_name='First_Name',
        ),
        migrations.RenameField(
            model_name='learners',
            old_name='IdProof',
            new_name='Id_Proof',
        ),
        migrations.RenameField(
            model_name='learners',
            old_name='LMSAccess',
            new_name='LMS_Access',
        ),
        migrations.RenameField(
            model_name='learners',
            old_name='LastName',
            new_name='Last_Name',
        ),
        migrations.RenameField(
            model_name='learners',
            old_name='Leadcreatedtime',
            new_name='Lead_Created_Time',
        ),
        migrations.RenameField(
            model_name='learners',
            old_name='LearnerOwner',
            new_name='Learner_Owner',
        ),
        migrations.RenameField(
            model_name='learners',
            old_name='ModeOfClass',
            new_name='Mode_Of_Class',
        ),
        migrations.RenameField(
            model_name='learners',
            old_name='PreferableTime',
            new_name='Preferable_Time',
        ),
        migrations.RenameField(
            model_name='learners',
            old_name='RegisteredCourse',
            new_name='Registered_Course',
        ),
        migrations.RenameField(
            model_name='learners',
            old_name='RegisteredDate',
            new_name='Registered_Date',
        ),
        migrations.RenameField(
            model_name='learners',
            old_name='SlackAccess',
            new_name='Slack_Access',
        ),
        migrations.RenameField(
            model_name='learners',
            old_name='TechStack',
            new_name='Tech_Stack',
        ),
    ]
