# Generated by Django 5.1.1 on 2024-09-27 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opportunities',
            old_name='demoattend_status',
            new_name='demoattended_stage',
        ),
    ]
