# Generated by Django 5.1.1 on 2024-09-27 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0002_rename_demoattend_status_opportunities_demoattended_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunities',
            name='date',
            field=models.DateField(),
        ),
    ]
