# Generated by Django 5.1.1 on 2024-09-28 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0003_alter_opportunities_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunities',
            name='TechStack',
            field=models.CharField(choices=[('Life Skills', 'Life Skills'), ('Study Abroad', 'Study Abroad'), ('HR', 'HR')], default='HR', max_length=24),
        ),
        migrations.AlterField(
            model_name='opportunities',
            name='batch_timing',
            field=models.CharField(choices=[('7AM-8AM', '7AM-8AM'), ('8AM-9AM', '8AM-9AM'), ('9AM-10AM', '9AM-10AM'), ('10AM-11AM', '10AM-11AM'), ('11AM-12PM', '11AM-12PM'), ('12PM-1PM', '12PM-1PM'), ('1PM-2PM', '1PM-2PM'), ('2PM-3PM', '2PM-3PM'), ('3PM-4PM', '3PM-4PM'), ('4PM-5PM', '4PM-5PM'), ('5PM-6PM', '5PM-6PM'), ('6PM-7PM', '6PM-7PM'), ('7PM-8PM', '7PM-8PM'), ('8PM-9PM', '8PM-9PM')], default='7AM-8AM', max_length=10),
        ),
        migrations.AlterField(
            model_name='opportunities',
            name='class_mode',
            field=models.CharField(choices=[('International Online', 'International Online'), ('India Online', 'India Online'), ('BLR Classroom', 'BLR Classroom'), ('HYD Classroom', 'HYD Classroom')], default='HYD Classroom', max_length=24),
        ),
        migrations.AlterField(
            model_name='opportunities',
            name='demoattended_stage',
            field=models.CharField(choices=[('None', 'None'), ('Ready To Join', 'Ready To Join'), ('Advanced Discussion', 'Advanced Discussion'), ('Call Not Answered', 'Call Not Answered'), ('Visiting', 'Visiting'), ('Fees Negotiation', 'Fees Negotiation'), ('Batch Allocation', 'Batch Allocation'), ('Need Time This Week', 'Need Time This Week'), ('Need Time Next Week', 'Need Time Next Week'), ('Need Time This Month', 'Need Time This Month'), ('Need Time Next Month', 'Need Time Next Month'), ('Special Requirements', 'Special Requirements'), ('Closed Own Register', 'Closed Own Register'), ('Closed Lost Cold Lead', 'Closed Lost Cold Lead')], default='None', max_length=30),
        ),
        migrations.AlterField(
            model_name='opportunities',
            name='lead_source',
            field=models.CharField(choices=[('None', 'None'), ('Walk In', 'Walk In'), ('Student Referral', 'Student Referral'), ('Demo', 'Demo'), ('Web Site', 'Web Site'), ('Web Site Chat', 'Web Site Chat'), ('Inbound Call', 'Inbound Call'), ('Google Ad Words', 'Google Ad Words'), ('Facebook Ads', 'Facebook Ads'), ('Google My Business', 'Google My Business'), ('WhatsApp Skill Capital', 'WhatsApp Skill Capital')], default='None', max_length=24),
        ),
        migrations.AlterField(
            model_name='opportunities',
            name='lostopportunity_reason',
            field=models.CharField(choices=[('None', 'None'), ('Invalid Number', 'Invalid Number'), ('Not Interested', 'Not Interested'), ('Joined Other Institute', 'Joined Other Institute'), ('Asking Free Course', 'Asking Free Course'), ('Pay After Placement', 'Pay After Placement')], default='Not Interested', max_length=30),
        ),
        migrations.AlterField(
            model_name='opportunities',
            name='opportunity_stage',
            field=models.CharField(choices=[('None', 'None'), ('Advanced Discussion', 'Advanced Discussion'), ('Ready To Join', 'Ready To Join'), ('Call Not Answered', 'Call Not Answered'), ('Visiting', 'Visiting'), ('Fees Negotiation', 'Fees Negotiation'), ('Batch Allocation', 'Batch Allocation'), ('Need Time This Week', 'Need Time This Week'), ('Need Time Next Week', 'Need Time Next Week'), ('Need Time This Month', 'Need Time This Month'), ('Need Time Next Month', 'Need Time Next Month'), ('Special Requirements', 'Special Requirements'), ('Closed Own Register', 'Closed Own Register'), ('Busy Asked A Call Back', 'Busy Asked A Call Back'), ('Closed Lost', 'Closed Lost')], default='None', max_length=30),
        ),
        migrations.AlterField(
            model_name='opportunities',
            name='opportunity_status',
            field=models.CharField(choices=[('Visiting', 'Visiting'), ('Visited', 'Visited'), ('Demo Attended', 'Demo Attended'), ('Lost Opportunity', 'Lost Opportunity')], default='Visited', max_length=30),
        ),
        migrations.AlterField(
            model_name='opportunities',
            name='visited_stage',
            field=models.CharField(choices=[('None', 'None'), ('Call Not Answered', 'Call Not Answered'), ('Ready To Join', 'Ready To Join'), ('Fees Negotiation', 'Fees Negotiation'), ('Batch Allocation', 'Batch Allocation'), ('Interested Demo', 'Interested Demo'), ('Special Requirements', 'Special Requirements'), ('Need Time This Week', 'Need Time This Week'), ('Need Time Next Week', 'Need Time Next Week'), ('Need Time This Month', 'Need Time This Month'), ('Need Time Next Month', 'Need Time Next Month'), ('Closed Own Register', 'Closed Own Register'), ('Closed Lost Cold Lead', 'Closed Lost Cold Lead')], default='None', max_length=30),
        ),
    ]
