# Generated by Django 5.1.1 on 2024-10-02 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0004_alter_opportunities_techstack_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opportunities',
            old_name='batch_timing',
            new_name='Batch_Timing',
        ),
        migrations.RenameField(
            model_name='opportunities',
            old_name='cc',
            new_name='CC',
        ),
        migrations.RenameField(
            model_name='opportunities',
            old_name='class_mode',
            new_name='Class_Mode',
        ),
        migrations.RenameField(
            model_name='opportunities',
            old_name='contact_no',
            new_name='Contact_No',
        ),
        migrations.RenameField(
            model_name='opportunities',
            old_name='date',
            new_name='Date',
        ),
        migrations.RenameField(
            model_name='opportunities',
            old_name='demoattended_stage',
            new_name='Demoattended_Stage',
        ),
        migrations.RenameField(
            model_name='opportunities',
            old_name='description',
            new_name='Description',
        ),
        migrations.RenameField(
            model_name='opportunities',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='opportunities',
            old_name='fee_coated',
            new_name='Fee_Coated',
        ),
        migrations.RenameField(
            model_name='opportunities',
            old_name='id',
            new_name='Id',
        ),
        migrations.RenameField(
            model_name='opportunities',
            old_name='lead_source',
            new_name='Lead_Source',
        ),
        migrations.RenameField(
            model_name='opportunities',
            old_name='lead_status',
            new_name='Lead_Status',
        ),
        migrations.RenameField(
            model_name='opportunities',
            old_name='lostopportunity_reason',
            new_name='Lost_Opportunity_Reason',
        ),
        migrations.RenameField(
            model_name='opportunities',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='opportunities',
            old_name='opportunity_stage',
            new_name='Opportunity_Stage',
        ),
        migrations.RenameField(
            model_name='opportunities',
            old_name='opportunity_status',
            new_name='Opportunity_Status',
        ),
        migrations.RenameField(
            model_name='opportunities',
            old_name='TechStack',
            new_name='Tech_Stack',
        ),
        migrations.RenameField(
            model_name='opportunities',
            old_name='visited_stage',
            new_name='Visited_Stage',
        ),
    ]
